function getPublications(){
    obj =[
            {"type":"journal", 
            "author":[  {"surname":"Chen", "name":"Kaiqiang"}, 
                        {"surname":"Gao", "name":"Xin"},
                        {"surname":"Yan", "name":"Menglong"},
                        {"surname":"Zhang", "name":"Yue"},
                        {"surname":"Sun", "name":"Xian"}
                    ],
            "title": "Building Extraction in Pixel Level from Aerial Imagery with Deep Convolutional Neural Networks",
            "journal":"Journal of Remote Sensing",
            "status":"accepted",
            "volume":"xx",
            "number":"",
            "issue": "",
            "pages":"xx",
            "year":"2019",
            "month":"",
            "doi":"xx"
            },
            {"type":"inproceedings",
            "author":[  {"surname":"Chen", "name":"Kaiqiang"},
                        {"surname":"Fu", "name":"Kun"},
                        {"surname":"Gao", "name":"Xin"},
                        {"surname":"Yan", "name":"Menglong"},
                        {"surname":"Zhang", "name":"Wenkai"},
                        {"surname":"Zhang", "name":"Yue"},
                        {"surname":"Sun", "name":"Xian"}
                    ],
            "title":"Effective Fusion of Multi-Modal Data with Group Convolutions for Semantic Segmentation of Aerial Imagery",
            "booktitle":"2018 IEEE International Geoscience and Remote Sensing Symposium (IGARSS)",
            "status":"published",
            "city":"Yokohama",
            "country":"Japan",
            "pages":"3911-3914",
            "volume":"",
            "number":"",
            "issue":"",
            "year":"2019",
            "month":"July",
            "doi":"10.1109/IGARSS.2019.8899217"
            },
            {"type":"inproceedings",
            "author":[  {"surname":"Jing", "name":"Hao"},
                        {"surname":"Feng", "name":"Yingchao"},
                        {"surname":"Zhang", "name":"Wenkai"},
                        {"surname":"Zhang", "name":"Yue"},
                        {"surname":"Wang", "name":"Siyue"},
                        {"surname":"Fu", "name":"Kun"},
                        {"surname":"Chen", "name":"Kaiqiang"}
                    ],
            "title":"Effective Classification of Local Climate Zones Based on Multi-Source Remote Sensing Data",
            "booktitle":"2018 IEEE International Geoscience and Remote Sensing Symposium (IGARSS)",
            "status":"published",
            "city":"Yokohama",
            "country":"Japan",
            "pages":"2666-2669",
            "volume":"",
            "number":"",
            "issue":"",
            "year":"2019",
            "month":"July",
            "doi":"10.1109/IGARSS.2019.8898475"
            },
            {"type":"inproceedings",
            "author":[  {"surname":"Chen", "name":"Kaiqiang"},
                        {"surname":"Weinmann","name":"Michael"},
                        {"surname":"Sun","name":"Xian"},
                        {"surname":"Yan", "name":"Menglong"},
                        {"surname":"Hinz", "name":"Stefan"},
                        {"surname":"Jutzi", "name":"Boris"},
                        {"surname":"Weinmann","name":"Martin"}
                    ],
            "title":"Semantic Segmentation of Aerial Imagery via Multi-Scale Shuffling Convolutional Neural Networks with Deep Supervision",
            "booktitle":"ISPRS Annals of Photogrammetry, Remote Sensing and Spatial Information Sciences",
            "status":"published",
            "city":"Karlsruhe",
            "country":"Germany",
            "pages":"29-36",
            "volume":"IV-1",
            "number":"",
            "issue":"",
            "year":"2018",
            "month":"September",
            "doi":"10.5194/isprs-annals-IV-1-29-2018"
            },
            {"type":"inproceedings",
            "author":[  {"surname":"Chen", "name":"Kaiqiang"},
                        {"surname":"Weinmann","name":"Michael"},
                        {"surname":"Gao","name":"Xin"},
                        {"surname":"Yan", "name":"Menglong"},
                        {"surname":"Hinz", "name":"Stefan"},
                        {"surname":"Jutzi", "name":"Boris"},
                        {"surname":"Weinmann","name":"Martin"}
                    ],
            "title":"Residual Shuffling Convolutional Neural Networks for Deep Semantic Image Segmentation Using Multi-Modal Data",
            "booktitle":"ISPRS Annals of Photogrammetry, Remote Sensing and Spatial Information Sciences",
            "status":"published",
            "city":"Riva del Garda",
            "country":"Italy",
            "pages":"65-72",
            "volume":"IV-2",
            "number":"",
            "issue":"",
            "year":"2018",
            "month":"June",
            "doi":"10.5194/isprs-annals-IV-2-65-2018"
            },
            {"type":"inproceedings",
            "author":[  {"surname":"Chen", "name":"Kaiqiang"},
                        {"surname":"Fu", "name":"Kun"},
                        {"surname":"Sun", "name":"Xian"},
                        {"surname":"Weinmann","name":"Michael"},
                        {"surname":"Hinz", "name":"Stefan"},
                        {"surname":"Jutzi", "name":"Boris"},
                        {"surname":"Weinmann","name":"Martin"}
                    ],
            "title":"Deep Semantic Segmentation of Aerial Imagery Based on Multi-Modal Data",
            "booktitle":"2018 IEEE International Geoscience and Remote Sensing Symposium, Valencia (IGARSS)",
            "status":"published",
            "city":"Valencia",
            "country":"Spain",
            "pages":"6219-6222",
            "volume":"",
            "number":"",
            "issue":"",
            "year":"2018",
            "month":"July",
            "doi":"10.1109/IGARSS.2018.8519225"
            },
            {"type":"journal", 
            "author":[  {"surname":"Chen", "name":"Kaiqiang"}, 
                        {"surname":"Fu", "name":"Kun"},
                        {"surname":"Yan", "name":"Menglong"},
                        {"surname":"Gao", "name":"Xin"},
                        {"surname":"Sun", "name":"Xian"},
                        {"surname":"Wei", "name":"Xin"}
                    ],
            "title": "Semantic Segmentation of Aerial Images With Shuffling Convolutional Neural Networks",
            "journal":"IEEE Geoscience and Remote Sensing Letters",
            "status":"published",
            "volume":"15",
            "number":"2",
            "issue": "",
            "pages":"173-177",
            "year":"2018",
            "month":"February",
            "doi":"10.1109/LGRS.2017.2778181"
            },
            {"type":"journal", 
            "author":[  {"surname":"Wei", "name":"Xin"}, 
                        {"surname":"Fu", "name":"Kun"},
                        {"surname":"Gao", "name":"Xin"},
                        {"surname":"Yan", "name":"Menglong"},
                        {"surname":"Sun", "name":"Xian"},
                        {"surname":"Chen", "name":"Kaiqiang"},                      
                        {"surname":"Sun", "name":"Hao"}
                    ],
            "title": "Semantic Pixel Labelling in Remote Sensing Images Using a Deep Convolutional Encoder-Decoder Model",
            "journal":"Remote Sensing Letters",
            "status":"published",
            "volume":"9",
            "number":"",
            "issue": "3",
            "pages":"199-208",
            "year":"2018",
            "month":"",
            "doi":"10.1080/2150704X.2017.1410291"
            },
            {"type":"journal", 
            "author":[  {"surname":"Zhang", "name":"Huan"}, 
                        {"surname":"Lei", "name":"Hong"},
                        {"surname":"Chen", "name":"Kaiqiang"}                     
                    ],
            "title": "Application of densely connected deconvolutional neural network in building extraction from remote sensing images",
            "journal":"Computer Engineering and Applications",
            "status":"published",
            "volume":"54",
            "number":"11",
            "issue": "",
            "pages":"140-144,152",
            "year":"2018",
            "month":"June",
            "doi":"10.3778/j.issn.1002-8331.1701-0316"
            },
            {"type":"inproceedings",
            "author":[  {"surname":"Chen", "name":"Kaiqiang"},
                        {"surname":"Fu", "name":"Kun"},
                        {"surname":"Gao","name":"Xin"},
                        {"surname":"Yan", "name":"Menglong"},
                        {"surname":"Sun", "name":"Xian"},
                        {"surname":"Zhang","name":"Huan"}
                    ],
            "title":"Building extraction from remote sensing images with deep learning in a supervised manner",
            "booktitle":"2017 IEEE International Geoscience and Remote Sensing Symposium, Valencia (IGARSS)",
            "status":"published",
            "city":"Fort Worth, TX",
            "country":"USA",
            "pages":"1672-1675",
            "volume":"",
            "number":"",
            "issue":"",
            "year":"2017",
            "month":"July",
            "doi":"10.1109/IGARSS.2017.8127295"
            },
            {"type":"inproceedings",
            "author":[  {"surname":"Zhang", "name":"Yue"},
                        {"surname":"Sun", "name":"Xian"},
                        {"surname":"Fu","name":"Kun"},
                        {"surname":"Chen", "name":"Kaiqiang"},
                        {"surname":"Wang", "name":"Hongqi"}
                    ],
            "title":"Flat-roofed building reconstruction based on layover modelling and MCMC method",
            "booktitle":"2017 IEEE International Geoscience and Remote Sensing Symposium, Valencia (IGARSS)",
            "status":"published",
            "city":"Fort Worth, TX",
            "country":"USA",
            "pages":"2287-2290",
            "volume":"",
            "number":"",
            "issue":"",
            "year":"2017",
            "month":"July",
            "doi":"10.1109/IGARSS.2017.8127446"
            }            
        ];

    return obj;
}